# Generated by Django 4.0.4 on 2022-06-03 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_dislikes_post_likes_delete_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
    ]
